import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, boolean, index, decimal, integer } from "drizzle-orm/pg-core";

// Better Auth schema generated by @better-auth/cli

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)]
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)]
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)]
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// ============================================================================
// Inventory Management Schema
// ============================================================================

// Categories (clothing types)
export const category = pgTable("category", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull(), // e.g., "Shirts", "Pants", "Dresses"
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Suppliers (where you buy lots from)
export const supplier = pgTable("supplier", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull(),
  phone: text("phone"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Lots (batches of clothing purchased from suppliers)
export const lot = pgTable(
  "lot",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    supplierId: text("supplier_id")
      .notNull()
      .references(() => supplier.id),

    purchaseCost: decimal("purchase_cost", { precision: 10, scale: 2 }).notNull(), // What you paid supplier
    washingCost: decimal("washing_cost", { precision: 10, scale: 2 }).default("0").notNull(), // Cost to wash clothes
    totalCost: decimal("total_cost", { precision: 10, scale: 2 }).notNull(), // purchaseCost + washingCost

    totalItems: integer("total_items").notNull(), // Number of items in lot
    costPerItem: decimal("cost_per_item", { precision: 10, scale: 2 }).notNull(), // totalCost / totalItems

    purchaseDate: timestamp("purchase_date").defaultNow().notNull(),
    notes: text("notes"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("lot_supplierId_idx").on(table.supplierId)]
);

// Products (individual clothing items)
export const product = pgTable(
  "product",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull(), // e.g., "Blue Denim Jacket"
    barcode: text("barcode"),
    categoryId: text("category_id").references(() => category.id),
    lotId: text("lot_id").references(() => lot.id), // Which lot this came from

    // Pricing
    costPrice: decimal("cost_price", { precision: 10, scale: 2 }).notNull(), // From lot.costPerItem
    sellingPrice: decimal("selling_price", { precision: 10, scale: 2 }).notNull(),

    // Stock (for second-hand, usually 1 per unique item, but can be more for similar items)
    stockQuantity: integer("stock_quantity").default(1).notNull(),

    isSold: boolean("is_sold").default(false).notNull(),
    soldAt: timestamp("sold_at"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("product_categoryId_idx").on(table.categoryId),
    index("product_lotId_idx").on(table.lotId),
    index("product_isSold_idx").on(table.isSold),
  ]
);

// Relations
export const categoryRelations = relations(category, ({ many }) => ({
  products: many(product),
}));

export const supplierRelations = relations(supplier, ({ many }) => ({
  lots: many(lot),
}));

export const lotRelations = relations(lot, ({ one, many }) => ({
  supplier: one(supplier, {
    fields: [lot.supplierId],
    references: [supplier.id],
  }),
  products: many(product),
}));

export const productRelations = relations(product, ({ one }) => ({
  category: one(category, {
    fields: [product.categoryId],
    references: [category.id],
  }),
  lot: one(lot, {
    fields: [product.lotId],
    references: [lot.id],
  }),
}));
